### ISSUE TITLE
Export DiceRule from @airjp73/dice-notation

### ISSUE THREAD

**Issue by n1ru4l** [airjp73/dice-notation#10]
Right now the DiceRole type must be imported via `import { DiceRule } from "@airjp73/dice-notation/dist/rules/types";` which is a bit ugly. It would be more clean if that type (and others) could be imported directly via `import { DiceRule } from "@airjp73/dice-notation";`

**Comment by airjp73** [comment]
That would be a nice DX feature. Would you mind making a PR?

**Comment by n1ru4l** [comment]
Yes I will send something over the next days :)
