### ISSUE TITLE
support + -

### ISSUE THREAD

**Issue by n1ru4l** [airjp73/dice-notation#8]
This formular should be parsable:

`1d20 + 5 + -2`

Error: Expected dice roll or constant but got operator (+)

**Comment by airjp73** [comment]
Hi @n1ru4l ! I could probably take a look at this over the weekend, or did you want to take a stab at it?

**Comment by n1ru4l** [comment]
@airjp73 It would be great if you could take a look at it! For now as I workaround I have a regex that replaces + - and - + with -. Alo stuff like - - and + + should probably be handled

**Comment by airjp73** [comment]
Oh totally -- it would be good to add full support for unary operators.

**Comment by airjp73** [comment]
Should be good now. Let me know if something goes wrong!

I put the changes in a PR if you want to take a look: #9 
Release: [1.2.0](https://github.com/airjp73/dice-notation/releases/tag/1.2.0)
